# Generated by Django 5.0.1 on 2024-02-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=255, null=True, verbose_name='Content'),
        ),
    ]
